import type { Metadata } from "next";
import "./globals.css";
import { initStoryblok } from "@/lib/storyblok";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { EB_Garamond } from "next/font/google";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "700"],
});

initStoryblok();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head></head>
      <body className={`min-h-full flex flex-col ${ebGaramond.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
